# Generated by Django 2.2.12 on 2020-10-20 18:42

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('choice', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('safe', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('test_urns', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('variance', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('endowment', otree.db.models.IntegerField(null=True)),
                ('option_1', otree.db.models.IntegerField(default=0, null=True, verbose_name='Triangle')),
                ('option_2', otree.db.models.IntegerField(default=0, null=True, verbose_name='Circle')),
                ('option_3', otree.db.models.IntegerField(default=0, null=True, verbose_name='Rectangle')),
                ('option_safe', otree.db.models.IntegerField(default=0, null=True, verbose_name='Hexagon')),
                ('urn_draws_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('urn_draws_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('urn_draws_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('urn_draws_4', otree.db.models.StringField(max_length=10000, null=True)),
                ('payoff_1', otree.db.models.CurrencyField(null=True)),
                ('payoff_2', otree.db.models.CurrencyField(null=True)),
                ('payoff_3', otree.db.models.CurrencyField(null=True)),
                ('payoff_4', otree.db.models.CurrencyField(null=True)),
                ('instru_page', otree.db.models.IntegerField(default=1, null=True)),
                ('questionnaire_page', otree.db.models.IntegerField(default=1, null=True)),
                ('controls', otree.db.models.IntegerField(default=0, null=True)),
                ('comprehension_page', otree.db.models.IntegerField(default=1, null=True)),
                ('completion_code', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_Pilot_1', otree.db.models.IntegerField(choices=[[9, 'I am not sure'], [1, 'Yes'], [99, 'No'], [999, 'Yes, but there is an additional option after 40 rounds']], default=0, null=True, verbose_name='In this HIT you repeatedly choose between a number of options. Do you get the same set of options in all rounds of the HIT?')),
                ('cq_Pilot_2', otree.db.models.IntegerField(choices=[[1, 'each point invested, i.e. each draw '], [9, 'one randomly chosen round'], [99, 'my performance in comparison to other workers'], [999, 'the last 20 rounds']], default=0, null=True, verbose_name='My total earnings depend on')),
                ('cq_Pilot_3', otree.db.models.IntegerField(choices=[[999, 'have the same average value'], [9, 'return a constant value'], [99, 'change over the course of the HIT'], [1, 'can differ in their average value']], default=0, null=True, verbose_name='All options')),
                ('cq_Pilot_4', otree.db.models.IntegerField(choices=[[999, 'need to invest all three points into one option'], [9, 'can not invest more than two points into one option'], [1, 'can choose to invest your three points however you want'], [99, 'can save points for later rounds']], default=0, null=True, verbose_name='In each round, you')),
                ('cq_Pilot_5', otree.db.models.IntegerField(choices=[[999, 'contain the same coins'], [9, 'return a constant value'], [99, 'change over the course of the HIT'], [1, 'can differ in their composition of coins']], default=0, null=True, verbose_name='All options')),
                ('access_device', otree.db.models.IntegerField(choices=[[0, 'Smartphone'], [1, 'Laptop'], [0, 'Tablet computer'], [1, 'Desktop PC']], null=True, verbose_name='')),
                ('attention_check_1', otree.db.models.IntegerField(choices=[[0, 'Never'], [0, 'Less than once a month'], [0, '1-3 times a month'], [0, 'Once a week'], [0, '2-3 times a week'], [0, '4-5 times a week'], [0, 'More than 5 times a week'], [1, 'Other']], null=True, verbose_name='')),
                ('attention_check_2', otree.db.models.StringField(blank=True, max_length=10000, null=True)),
                ('q_risk', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10']], null=True, verbose_name='How do you see yourself: are you generally a person who is fully prepared to take risks or do you try to avoid taking risks?')),
                ('q_exploration_strategy', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_firm', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_fadein', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_fadeout', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_saving', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_wealth', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_maxoption', otree.db.models.IntegerField(choices=[[1, 'Triangle'], [2, 'Circle'], [3, 'Rectangle'], [4, 'Hexagon']], null=True, verbose_name='')),
                ('q_maxoption_2', otree.db.models.IntegerField(choices=[[1, 'Triangle'], [2, 'Circle'], [3, 'Rectangle']], null=True, verbose_name='')),
                ('q_maxoption_3', otree.db.models.IntegerField(choices=[[1, 'Triangle'], [2, 'Circle'], [3, 'Rectangle'], [4, 'Hexagon'], [5, 'In the long run, they would all return the same value']], null=True, verbose_name='')),
                ('q_year', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('q_sex', otree.db.models.IntegerField(choices=[[1, 'Male'], [2, 'Female'], [3, 'Prefer not to answer']], null=True, verbose_name='')),
                ('q_employment', otree.db.models.IntegerField(choices=[[1, 'Working (paid employee)'], [2, 'Working (self-employed)'], [3, 'Not working (temporary layoff from a job)'], [4, 'Not working (looking for work)'], [5, 'Not working (retired)'], [6, 'Not working (disabled)'], [7, 'Not working (other)'], [8, 'Prefer not to answer']], null=True, verbose_name='')),
                ('q_education', otree.db.models.IntegerField(choices=[[1, 'Less than high school degree'], [2, 'High school graduate (high school diploma or equivalent including GED)'], [3, 'Some college but no degree'], [4, 'Associate degree in college (2-year)'], [5, 'Bachelor’s degree in college(4 - year)'], [6, 'Master’s degree'], [7, 'Doctoral degree'], [8, 'Professional degree (JD, MD)']], null=True, verbose_name='')),
                ('q_ethnicity', otree.db.models.StringField(max_length=10000, null=True, verbose_name='')),
                ('q_imi_1', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I enjoyed doing this task very much.')),
                ('q_imi_2', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='This task was fun to do.')),
                ('q_imi_3', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I thought this was a boring task.')),
                ('q_imi_4', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='This task did not hold my attention at all.')),
                ('q_imi_5', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I would describe this task as very interesting.')),
                ('q_imi_6', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I thought this task was quite enjoyable.')),
                ('q_imi_7', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='While I was doing this task, I was thinking about how much I enjoyed it.')),
                ('q_epo_1', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Before I act I consider what I will gain or lose in the future as a result of my actions.')),
                ('q_epo_2', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I try to anticipate as many consequences of my actions as I can.')),
                ('q_epo_3', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Before I make a decision I consider all possible outcomes.')),
                ('q_epo_4', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I always try to assess how important the potential consequences of my decisions might be.')),
                ('q_epo_5', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I try hard to predict how likely different consequences are.')),
                ('q_epo_6', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Usually I carefully estimate the risk of various outcomes occurring.')),
                ('q_epo_7', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I keep a positive attitude that things always turn out all right.')),
                ('q_epo_8', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I prefer to think about the good things that can happen rather than the bad.')),
                ('q_epo_9', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='When thinking over my decisions I focus more on their positive end results.')),
                ('q_epo_10', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I tend to think a lot about the negative outcomes that might occur as a result of my actions.')),
                ('q_epo_11', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I am often afraid that things might turn out badly.')),
                ('q_epo_12', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='When thinking over my decisions I focus more on their negative end results.')),
                ('q_epo_13', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I often worry about what could go wrong as a result of my decisions.')),
                ('q_max_scale_1', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='No matter how satisfied I am with my job, it’s only right for me to be on the lookout for better opportunities.')),
                ('q_max_scale_2', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='When I am in the car listening to the radio, I often check other stations to see if something better is playing, even if I am relatively satisfied with what I’m listening to.')),
                ('q_max_scale_3', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I often find it difficult to shop for a gift for a friend')),
                ('q_max_scale_4', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='Choosing a tv show or a movie to watch is really difficult. I’m always struggling to pick the best one.')),
                ('q_max_scale_5', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='I never settle for second best.')),
                ('q_max_scale_6', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='No matter what I do, I have the highest standards for myself.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pilot.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilot.Subsession')),
            ],
            options={
                'db_table': 'Pilot_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilot.Subsession'),
        ),
    ]
