# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('choice', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('endowment', otree.db.models.IntegerField(null=True)),
                ('option_1', otree.db.models.IntegerField(null=True)),
                ('option_2', otree.db.models.IntegerField(null=True)),
                ('option_3', otree.db.models.IntegerField(null=True)),
                ('option_safe', otree.db.models.IntegerField(null=True)),
                ('access_device', otree.db.models.IntegerField(choices=[[0, 'Smartphone'], [1, 'Laptop'], [0, 'Tablet computer'], [1, 'Desktop PC']], null=True, verbose_name='')),
                ('attention_check_1', otree.db.models.IntegerField(choices=[[0, 'Never'], [0, 'Less than once a month'], [0, '1-3 times a month'], [0, 'Once a week'], [0, '2-3 times a week'], [0, '4-5 times a week'], [0, 'More than 5 times a week'], [1, 'Other']], null=True, verbose_name='')),
                ('attention_check_2', otree.db.models.StringField(blank=True, max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pilot.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_player', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilot.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilot.Subsession'),
        ),
    ]
