# Generated by Django 2.2.12 on 2020-08-24 11:31

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Pilot_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('choice', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('safe', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('test_urns', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('endowment', otree.db.models.IntegerField(null=True)),
                ('option_1', otree.db.models.IntegerField(default=0, null=True, verbose_name='Triangle')),
                ('option_2', otree.db.models.IntegerField(default=0, null=True, verbose_name='Square')),
                ('option_3', otree.db.models.IntegerField(default=0, null=True, verbose_name='Rectangle')),
                ('option_safe', otree.db.models.IntegerField(default=0, null=True, verbose_name='Hexagon')),
                ('urn_draws_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('urn_draws_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('urn_draws_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('urn_draws_4', otree.db.models.StringField(max_length=10000, null=True)),
                ('payoff_1', otree.db.models.CurrencyField(null=True)),
                ('payoff_2', otree.db.models.CurrencyField(null=True)),
                ('payoff_3', otree.db.models.CurrencyField(null=True)),
                ('payoff_4', otree.db.models.CurrencyField(null=True)),
                ('instru_page', otree.db.models.IntegerField(default=1, null=True)),
                ('questionnaire_page', otree.db.models.IntegerField(default=1, null=True)),
                ('controls', otree.db.models.IntegerField(default=0, null=True)),
                ('comprehension_page', otree.db.models.IntegerField(default=1, null=True)),
                ('cq_Pilot_1', otree.db.models.IntegerField(choices=[[9, 'I am not sure'], [1, 'Yes'], [99, 'No'], [999, 'Yes, but there is an additional option after 40 rounds']], default=0, null=True, verbose_name='In this HIT you repeatedly choose between a number of options. Do you get the same set of options in all rounds of the HIT?')),
                ('cq_Pilot_2', otree.db.models.IntegerField(choices=[[1, 'each point invested, i.e. each draw '], [9, 'one randomly chosen round'], [99, 'my performance in comparison to other workers'], [999, 'the last 20 rounds']], default=0, null=True, verbose_name='My total earnings depend on')),
                ('cq_Pilot_3', otree.db.models.IntegerField(choices=[[999, 'have the same average value'], [9, 'return a constant value'], [99, 'change over the course of the HIT'], [1, 'can differ in their average value']], default=0, null=True, verbose_name='All options')),
                ('cq_Pilot_4', otree.db.models.IntegerField(choices=[[999, 'need to invest all three points into one option'], [9, 'can not invest more than two points into one option'], [1, 'can choose to invest your three points however you want'], [99, 'can save points for later rounds']], default=0, null=True, verbose_name='In each round, you')),
                ('access_device', otree.db.models.IntegerField(choices=[[0, 'Smartphone'], [1, 'Laptop'], [0, 'Tablet computer'], [1, 'Desktop PC']], null=True, verbose_name='')),
                ('attention_check_1', otree.db.models.IntegerField(choices=[[0, 'Never'], [0, 'Less than once a month'], [0, '1-3 times a month'], [0, 'Once a week'], [0, '2-3 times a week'], [0, '4-5 times a week'], [0, 'More than 5 times a week'], [1, 'Other']], null=True, verbose_name='')),
                ('attention_check_2', otree.db.models.StringField(blank=True, max_length=10000, null=True)),
                ('q_risk', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10']], null=True, verbose_name='How do you see yourself: are you generally a person who is fully prepared to take risks or do you try to avoid taking risks?')),
                ('q_exploration_strategy', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_firm', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_fadein', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_fadeout', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_saving', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_wealth', otree.db.models.LongStringField(null=True, verbose_name='')),
                ('q_maxoption', otree.db.models.IntegerField(choices=[[1, 'Triangle'], [2, 'Square'], [3, 'Rectangle'], [4, 'Hexagon']], null=True, verbose_name='')),
                ('q_maxoption_2', otree.db.models.IntegerField(choices=[[1, 'Option Triangle'], [2, 'Option Square'], [3, 'Option Rectangle']], null=True, verbose_name='')),
                ('q_year', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('q_sex', otree.db.models.IntegerField(choices=[[1, 'Male'], [2, 'Female'], [3, 'Prefer not to answer']], null=True, verbose_name='')),
                ('q_employment', otree.db.models.IntegerField(choices=[[1, 'Working (paid employee)'], [2, 'Working (self-employed)'], [3, 'Not working (temporary layoff from a job)'], [4, 'Not working (looking for work)'], [5, 'Not working (retired)'], [6, 'Not working (disabled)'], [7, 'Not working (other)'], [8, 'Prefer not to answer']], null=True, verbose_name='')),
                ('q_education', otree.db.models.IntegerField(choices=[[1, 'Less than high school degree'], [2, 'High school graduate (high school diploma or equivalent including GED)'], [3, 'Some college but no degree'], [4, 'Associate degree in college (2-year)'], [5, 'Bachelor’s degree in college(4 - year)'], [6, 'Master’s degree'], [7, 'Doctoral degree'], [8, 'Professional degree (JD, MD)']], null=True, verbose_name='')),
                ('q_ethnicity', otree.db.models.StringField(max_length=10000, null=True, verbose_name='')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pilot.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilot.Subsession')),
            ],
            options={
                'db_table': 'Pilot_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pilot.Subsession'),
        ),
    ]
