# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 17:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0003_auto_20200715_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draws_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='draws_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='draws_3',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
