# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-15 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0004_auto_20200715_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='draws_1',
        ),
    ]
