# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-16 07:58
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0006_auto_20200715_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payoff',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payoff_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payoff_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payoff_3',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
