# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-16 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0008_auto_20200716_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='option_safe',
        ),
    ]
