# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-16 09:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0009_auto_20200716_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='option_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='option_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='option_3',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='option_safe',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
