# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-17 08:07
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0014_auto_20200716_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='safe',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
