# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-17 08:40
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0015_player_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='urn_draws_4',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
