# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-17 08:40
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0016_player_urn_draws_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payoff_4',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
