# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-17 13:52
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0017_player_payoff_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='instru_page',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
